version: "3"
services:
  node-app:
    build:
      context: .
      target: production
      # args:
      #   - NODE_ENV=development
    environment:
      - NODE_ENV=production
    command: npm run start